Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebdoAn.Models;

namespace WebdoAn.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebdoAn.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SingleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebdoAn.Models;

namespace WebdoAn.Controllers
{
    public class SingleController : Controller
    {
        // GET: Single
        SalesOnlineEntities1 data = new SalesOnlineEntities1();
        public ActionResult Index(string id)
        {
            var sanpham = from s in data.sanPhams
                          where s.maSP == id
                          select s;
            return View(sanpham.Single());
        }
    }
}

Views/Home/Index.cshtml
@using WebdoAn.Models
@{
    ViewBag.Title = "Home Page";
}
<div class="container">
    <div class="shoes-grid">
        <a href="@Url.Action("Index","Single",null,Request.Url.Scheme)">
            <div class="wrap-in">
                <div class="wmuSlider example1 slide-grid">
                    <div class="wmuSliderWrapper">
                        <article style="position: absolute; width: 100%; opacity: 0;">
                            <div class="banner-matter">
                                <div class="col-md-5 banner-bag">
                                    <img class="img-responsive " src="~/Assets/Images/bag.jpg" alt=" " />
                                </div>
                                <div class="col-md-7 banner-off">
                                    <h2>FLAT 50% 0FF</h2>
                                    <label>FOR ALL PURCHASE <b>VALUE</b></label>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et </p>
                                    <span class="on-get">GET NOW</span>
                                </div>

                                <div class="clearfix"> </div>
                            </div>

                        </article>
                        <article style="position: absolute; width: 100%; opacity: 0;">
                            <div class="banner-matter">
                                <div class="col-md-5 banner-bag">
                                    <img class="img-responsive " src="~/Assets/Images/bag1.jpg" alt=" " />
                                </div>
                                <div class="col-md-7 banner-off">
                                    <h2>FLAT 50% 0FF</h2>
                                    <label>FOR ALL PURCHASE <b>VALUE</b></label>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et </p>
                                    <span class="on-get">GET NOW</span>
                                </div>

                                <div class="clearfix"> </div>
                            </div>

                        </article>
                        <article style="position: absolute; width: 100%; opacity: 0;">
                            <div class="banner-matter">
                                <div class="col-md-5 banner-bag">
                                    <img class="img-responsive " src="~/Assets/Images/bag.jpg" alt=" " />
                                </div>
                                <div class="col-md-7 banner-off">
                                    <h2>FLAT 50% 0FF</h2>
                                    <label>FOR ALL PURCHASE <b>VALUE</b></label>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et </p>
                                    <span class="on-get">GET NOW</span>
                                </div>

                                <div class="clearfix"> </div>
                            </div>

                        </article>
                    </div>
        </a>
        <ul class="wmuSliderPagination">
            <li><a href="#" class="">0</a></li>
            <li><a href="#" class="">1</a></li>
            <li><a href="#" class="">2</a></li>
        </ul>
        <script src="~/Scripts/jquery.wmuSlider.js"></script>
        <script>
            $('.example1').wmuSlider();
        </script>
    </div>
</div>
    </a>
<!---->
<div class="shoes-grid-left">
    <a href="@Url.Action("Index","Single",null,Request.Url.Scheme)">
        <div class="col-md-6 con-sed-grid">

            <div class=" elit-grid">

                <h4>consectetur  elit</h4>
                <label>FOR ALL PURCHASE VALUE</label>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, </p>
                <span class="on-get">GET NOW</span>
            </div>
            <img class="img-responsive shoe-left" src="~/Assets/Images/sh.jpg" alt=" " />

            <div class="clearfix"> </div>

        </div>
    </a>
    <a href="@Url.Action("Index","Single",null,Request.Url.Scheme)">
        <div class="col-md-6 con-sed-grid sed-left-top">
            <div class=" elit-grid">
                <h4>consectetur  elit</h4>
                <label>FOR ALL PURCHASE VALUE</label>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, </p>
                <span class="on-get">GET NOW</span>
            </div>
            <img class="img-responsive shoe-left" src="~/Assets/Images/wa.jpg" alt=" " />

            <div class="clearfix"> </div>
        </div>
    </a>
</div>
<div class="products">
    <h5 class="latest-product">LATEST PRODUCTS</h5>
    <a class="view-all" href="@Url.Action("Index","Product",null,Request.Url.Scheme)">VIEW ALL<span> </span></a>
</div>
@{
    CommonData y = (CommonData)HttpContext.Current.Application["All"];

}
<div class="product-left">
    @foreach (sanPham i in y.Sanphammoi(6))
    {
        <div class="col-md-4 chain-grid grid-top-chain" style="width: 29.7%;height: 466px;">
            <a href="@Url.Action("Index","Single",new {id=i.maSP })"><img class="img-responsive chain" style="width: 150px;height: 300px;" src="@i.hinhDD" alt="@i.tenSP " /></a>
            <span class="star"> </span>
            <div class="grid-chain-bottom">
                <h6><a href="@Url.Action("Index","Single", new {id=i.maSP })">@i.tenSP</a></h6>
                <div class="star-price">
                    <div class="dolor-grid">
                        <span class="actual">@i.giaBan</span>
                        <span class="reducedfrom">@i.giaBan</span>
                        <span class="rating">
                            <input type="radio" class="rating-input" id="rating-input-1-5" name="rating-input-1">
                            <label for="rating-input-1-5" class="rating-star1"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-4" name="rating-input-1">
                            <label for="rating-input-1-4" class="rating-star1"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-3" name="rating-input-1">
                            <label for="rating-input-1-3" class="rating-star"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-2" name="rating-input-1">
                            <label for="rating-input-1-2" class="rating-star"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-1" name="rating-input-1">
                            <label for="rating-input-1-1" class="rating-star"> </label>
                        </span>
                    </div>
                    <a href="@Url.Action("ThemGioHang","Giohang",new {@sMaSP=i.maSP,@strURL=Request.Url.ToString() })" class="now-get get-cart" >ADD TO CART</a>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
    }
    @*<div class="col-md-4 chain-grid">
            <a href="@Url.Action("Index","Single",null,Request.Url.Scheme)"><img class="img-responsive chain" src="~/Assets/Images/ba.jpg" alt=" " /></a>
            <span class="star"> </span>
            <div class="grid-chain-bottom">
                <h6><a href="@Url.Action("Index","Single",null,Request.Url.Scheme)">Lorem ipsum dolor</a></h6>
                <div class="star-price">
                    <div class="dolor-grid">
                        <span class="actual">300$</span>
                        <span class="reducedfrom">400$</span>
                        <span class="rating">
                            <input type="radio" class="rating-input" id="rating-input-1-5" name="rating-input-1">
                            <label for="rating-input-1-5" class="rating-star1"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-4" name="rating-input-1">
                            <label for="rating-input-1-4" class="rating-star1"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-3" name="rating-input-1">
                            <label for="rating-input-1-3" class="rating-star"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-2" name="rating-input-1">
                            <label for="rating-input-1-2" class="rating-star"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-1" name="rating-input-1">
                            <label for="rating-input-1-1" class="rating-star"> </label>
                        </span>
                    </div>
                    <a class="now-get get-cart" href="#">ADD TO CART</a>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 chain-grid grid-top-chain">
            <a href="@Url.Action("Index","Single",null,Request.Url.Scheme)"><img class="img-responsive chain" src="~/Assets/Images/bo.jpg" alt=" " /></a>
            <span class="star"> </span>
            <div class="grid-chain-bottom">
                <h6><a href="@Url.Action("Index","Single",null,Request.Url.Scheme)">Lorem ipsum dolor</a></h6>
                <div class="star-price">
                    <div class="dolor-grid">
                        <span class="actual">300$</span>
                        <span class="reducedfrom">400$</span>
                        <span class="rating">
                            <input type="radio" class="rating-input" id="rating-input-1-5" name="rating-input-1">
                            <label for="rating-input-1-5" class="rating-star1"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-4" name="rating-input-1">
                            <label for="rating-input-1-4" class="rating-star1"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-3" name="rating-input-1">
                            <label for="rating-input-1-3" class="rating-star"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-2" name="rating-input-1">
                            <label for="rating-input-1-2" class="rating-star"> </label>
                            <input type="radio" class="rating-input" id="rating-input-1-1" name="rating-input-1">
                            <label for="rating-input-1-1" class="rating-star"> </label>
                        </span>
                    </div>
                    <a class="now-get get-cart" href="#">ADD TO CART</a>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>*@
    <div class="clearfix"> </div>
</div>
<div class="products">
    <h5 class="latest-product">LATEST PRODUCTS</h5>
    <a class="view-all" href="@Url.Action("Index","Product",null,Request.Url.Scheme)">VIEW ALL<span> </span></a>
</div>
<div class="product-left">
    @foreach (sanPham i in y.Sanphammoi(3))
    {
    <div class="col-md-4 chain-grid grid-top-chain"style="width: 29.7%;height: 466px;">
        <a href="@Url.Action("Index", "Single", new {id=i.maSP })"><img class="img-responsive chain"style="width: 150px;height: 300px;" src="@i.hinhDD" alt="@i.tenSP" /></a>
        <span class="star"> </span>
        <div class="grid-chain-bottom">
            <h6><a href="@Url.Action("Index", "Single",new {id=i.maSP })">@i.tenSP</a></h6>
            <div class="star-price">
                <div class="dolor-grid">
                    <span class="actual">@i.giaBan</span>
                    <span class="reducedfrom">@i.giaBan</span>
                    <span class="rating">
                        <input type="radio" class="rating-input" id="rating-input-1-5" name="rating-input-1">
                        <label for="rating-input-1-5" class="rating-star1"> </label>
                        <input type="radio" class="rating-input" id="rating-input-1-4" name="rating-input-1">
                        <label for="rating-input-1-4" class="rating-star1"> </label>
                        <input type="radio" class="rating-input" id="rating-input-1-3" name="rating-input-1">
                        <label for="rating-input-1-3" class="rating-star"> </label>
                        <input type="radio" class="rating-input" id="rating-input-1-2" name="rating-input-1">
                        <label for="rating-input-1-2" class="rating-star"> </label>
                        <input type="radio" class="rating-input" id="rating-input-1-1" name="rating-input-1">
                        <label for="rating-input-1-1" class="rating-star"> </label>
                    </span>
                </div>
                <a class="now-get get-cart" href="@Url.Action("ThemGioHang","Giohang",new {@sMaSP=i.maSP,@strURL=Request.Url.ToString() })">ADD TO CART</a>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
     }
        <div class="clearfix"> </div>
    </div>
<div class="clearfix"> </div>
    </div>

    </div>